manifest = "66339cd27fcb5adb170a5b500094d2be0f6bcae12b3920b93bc1a503f7be7825"

[[dependency]]
package = "github.com/buckaroo-pm/xiph-ogg"
target = "//:ogg"

[lock."github.com/buckaroo-pm/xiph-ogg"]
versions = [ "branch=master" ]
revision = "eb31a551c48339c07aa2af9fb8baeac7988f4f81"
