manifest = "206657866238824d1f98e392b83b3b39d4e9e45afc02565ab434905e83ae43d5"

[[dependency]]
package = "github.com/buckaroo-pm/xiph-ogg"
target = "//:ogg"

[lock."github.com/buckaroo-pm/xiph-ogg"]
versions = [ "branch=master" ]
revision = "eb31a551c48339c07aa2af9fb8baeac7988f4f81"
