manifest = "206657866238824d1f98e392b83b3b39d4e9e45afc02565ab434905e83ae43d5"

[[dependency]]
package = "github.com/buckaroo-pm/xiph-ogg"
target = "//:ogg"

[[lock]]
name = "github.com/buckaroo-pm/xiph-ogg"
revision = "82b18eecd378eff6f5fd77db8c49cc1f8deeadff"
